trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - docs/**
      - .gitignore
      - .git/**
      - .github/**
      - .vscode/**

variables:
  - group: mvp-secrets
  - name: IMAGE_TAG
    value: $(Build.BuildId)

stages:
  - stage: Build
    displayName: "Build & Push Docker Images"
    jobs:
      - job: BuildImages
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: "Login al ACR"
            inputs:
              command: login
              containerRegistry: acr-service-connection

          - task: Docker@2
            displayName: "Build y Push Backend"
            inputs:
              command: buildAndPush
              repository: backend
              dockerfile: Backend/Dockerfile
              buildContext: Backend
              containerRegistry: acr-service-connection
              tags: |
                $(IMAGE_TAG)
                latest

          - task: Docker@2
            displayName: "Build Frontend"
            inputs:
              command: build
              repository: frontend
              dockerfile: Frontend/Dockerfile
              buildContext: Frontend
              containerRegistry: acr-service-connection
              arguments: '--build-arg VITE_BACKEND_URL=$(VITE_BACKEND_URL)'
              tags: |
                $(IMAGE_TAG)
                latest

          - task: Docker@2
            displayName: "Push Frontend"
            inputs:
              command: push
              repository: frontend
              containerRegistry: acr-service-connection
              tags: |
                $(IMAGE_TAG)
                latest
